language: java
jdk:
  - oraclejdk8
script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -e -Ppackagecloud test deploy
after_failure:
  - echo "\n=== SUREFIRE REPORTS ===\n"
  - for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done
